### ISSUE TITLE
Add Documentation and Tests for GraphConstructorSpatial

### ISSUE THREAD

**Issue by jernsting** [wwu-mmll/photonai_graph#65]
GraphConstructorSpatial requires a `atlas_name_coords.csv`. Please provide an example.
Is this constructor intedet for DTI or RestingState data?
Why is the default atlas HO not tested? Why is it not contained in the graph package?

**Comment by jernsting** [comment]
Please also remove warning (untested) from documentation: https://wwu-mmll.github.io/photonai_graph/api/graph_construction/#graphconstructorspatial

**Comment by VHolstein** [comment]
- [ ] Is this constructor intended for DTI or RestingState data? -> Can be used for both DTI and Resting State (already in docs), expanding documentation even further
- [ ] Why is default atlas HO not tested -> atlas is tested see test_ho_atlas, can add a second test if needed
- [ ] default ho_atlas is contained in tests, comes from ABIDE and is not distributed as part of the package due to a lack of clarity concerning license issues
